clear
clc
%% Test message boxes and message button boxes

% Msg box
msgfig = msgbox({'-- How to play --'; ...
        'You are the white square, and you must traverse the maze to reach the flag (Grey square)'; ...
        'Control the white square with ''WASD'' or your arrows Key!'; ...
        'To spice up gameplay, the maze becomes more difficult every 3rd level you complete!'; ...
        'If the game is not responding to key presses, click on the maze window to focus!'; ...
        'Finally, you can access special features with the ''Q'' key, or quit the game with ''X'' key'; ...
        '== Have Fun!! =='},'Welcome!','modal');
uiwait(msgfig) % Waits until accepted to coninue

% UI Button Src: https://au.mathworks.com/help/matlab/ref/uibutton.html
% Button functionality
fig = uifigure;
label = uilabel(fig, ...
            'Text', 'This is a label', ...
            'Position', [20, 100, 100, 22], ... 
            'FontSize', 12);
button = uibutton(fig, ...
    'Text', 'CLICK ME!', ...
    'Position', [120, 100, 100, 22]); % Adjust width

% Add functionality to button
button.ButtonPushedFcn = @(src, event) disp(['Button has been clicked']);
